python -u main.py \
--num_workers 4 \
--batch_size 128 \
--input_type 'spec' \
--w2v_type 'google' \
--is_balanced True \
--is_weighted True \
--data_path '/home/minz.s.won/data/pandora' \
--model_save_path './checkpoints/b-w-spec-google' \
--neptune_project 'minzwon/pandora' \
--neptune_api_key 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiZWJkZGQzNTctNTllZC00ZDg0LTlkZTMtMWZkYThjZjRkMDQwIn0='
